const PLANS = {
  BASIC: {
    name: 'Basic',
    slug: 'basic',
    price: 139500, // in paise (INR)
    features: [
      'FREE 500 Ad Credits (one-time)',
      'Free WhatsApp Business API',
      'Free WhatsApp Blue Tick Application',
      'AI Template message generator',
      'Unlimited Broadcasting & Retargeting',
      'Unlimited Free Service Conversations',
      'Click to WhatsApp Ads Manager',
      'Upload & Manage Contacts',
      'Create tags & attributes',
      'Upto 10 Tags',
      'Upto 5 Custom Attributes',
      'Create template messages',
      'Live Chat Dashboard',
      '1 Owner + 5 FREE Agents included',
      'Smart Audience Segregation',
      'Template Message APIs',
      'Multi-Agent Live Chat',
      'Agent Transfer & Manager Monitoring',
      'AiSensy Marketplace Integrations',
      'Shopify & WooCommerce Integrations',
      'Shared Team Inbox',
      'WhatsApp Payments',
    ],
    limits: { contacts: -1, campaigns: -1, messages: -1, agents: 5, tags: 10, customAttributes: 5 },
  },
  PRO: {
    name: 'Pro',
    slug: 'pro',
    price: 299900,
    features: [
      'FREE 500 Ad Credits (one-time)',
      'Everything in Basic Plan',
      'Upto 100 Tags',
      'Upto 20 Custom Attributes',
      'Campaign Scheduler',
      'Campaign Click Tracking',
      'Smart Agent Routing',
      'Campaign Budget Analytics',
      'Project APIs',
      'Custom Agent Rules',
      'Carousel Template Click Tracking',
      'CSV Campaign Scheduler',
      'User Access Control',
      'Automatic Failed Message Retry',
      '1 Owner + 5 FREE Agents included',
    ],
    limits: { contacts: -1, campaigns: -1, messages: -1, agents: 5, tags: 100, customAttributes: 20 },
  },
};

module.exports = { PLANS };
